{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "thanos.fullname" . }}-thanos-tls
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  server.crt: {{ .Values.tls.server.crt | b64enc }}
  server.key: {{ .Values.tls.server.key | b64enc }}
  client.crt: {{ .Values.tls.client.crt | b64enc }}
  client.key: {{ .Values.tls.client.key | b64enc }}
  ca.crt: {{ .Values.tls.chain | b64enc }}

---

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "thanos.fullname" . }}-thanos-ingress-tls
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  tls.crt: {{ .Values.tls.server.crt | b64enc }}
  tls.key: {{ .Values.tls.server.key | b64enc }}

---

apiVersion: v1
kind: Secret
type: Opaque
name: {{ include "thanos.fullname" . }}-thanos-ca-secret
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ca.crt: {{ .Values.tls.chain | b64enc }}
{{- end }}
